select 
    s.PRODUCTKEY,
    SUM(S.TOTALPRODUCTCOST) AS TOTAL_PRODUCT_COST,
    (SUM(S.SALESAMOUNT) - SUM(S.TOTALPRODUCTCOST)) / NULLIF(SUM(S.SALESAMOUNT), 0) AS PROFIT_MARGIN
from {{ ref('stg_bike_sales_sales') }} as s
GROUP BY s.PRODUCTKEY